version: "3"

services:

  node-app:
    build:
      context: .         
      dockerfile: Dockerfile  
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app

  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100    

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prom-server
      - loki
